* RubyNEAT Panel

** Description
   RubyNEAT Panel is a dashboard interface to monitor the activities of RubyNEAT. It
   utilizes the FOX libraries to create a portable GUI to allow to to see and control
   RubyNEAT in a graphical manner, and to explore the structure of the neural nets.
   
** Features
** Installation
   You will need the native Fox libraries installed on your
   system. Please see [[https://github.com/larskanis/fxruby#install][FxRuby Installation]] for the details. You needen't concern
   yourself with the details of the actual gem installation of fxruby, because
   it is listed as a dependency, anyway, by rubyneat-panel

   From command-line:
   #+BEGIN_SRC bash
   gem install rubyneat-panel
   #+END_SRC

   Or from a gemfile:
   #+BEGIN_SRC ruby
   gem 'rubyneat-panel'
   #+END_SRC

*** TODO Setup with RubyNEAT

** Documentation
** TODO Release Notes and Known Issues
*** TODO Release Notes
*** TODO Known Issues

** Contributing to rubyneat-panel
 
   - Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
   - Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
   - Fork the project.
   - Start a feature/bugfix branch.
   - Commit and push until you are happy with your contribution.
   - Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
   - Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

** Copyright

   Copyright (c) 2016-2017 Fred Mitchell. See LICENSE.txt for
   further details.
