# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rubyneat-panel 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rubyneat-panel".freeze
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Fred Mitchell".freeze]
  s.date = "2016-12-24"
  s.description = "TODO: longer description of your gem".freeze
  s.email = "fred.mitchell@gmx.de".freeze
  s.executables = ["neat-panel".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.org"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-version",
    ".semver",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.org",
    "Rakefile",
    "bin/neat-panel",
    "images/RubyNEAT_logo_full.xcf",
    "images/gems.blend",
    "images/gems.blend1",
    "images/panel-icon.xcf",
    "images/panel-logo-100h.png",
    "images/panel-logo-100h.xcf",
    "images/panel-logo.xcf",
    "images/ruby.blend",
    "images/ruby.blend1",
    "images/ruby0.01.blend",
    "images/ruby0.01.blend1",
    "images/rubyneat-test.png",
    "lib/rubyneat-panel.rb",
    "lib/rubyneat-panel/assets.rb",
    "lib/rubyneat-panel/cli.rb",
    "lib/rubyneat-panel/critters.fx",
    "lib/rubyneat-panel/main.fx",
    "lib/rubyneat-panel/main.rb",
    "lib/rubyneat-panel/overview.fx",
    "lib/rubyneat-panel/overview_rabbit_channels.fx",
    "lib/rubyneat-panel/overview_rabbit_details.fx",
    "lib/rubyneat-panel/settings.fx",
    "lib/rubyneat-panel/stats.fx",
    "spec/rubyneat-panel_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/flajann2/rubyneat-panel".freeze
  s.licenses = ["MIT".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.3.1".freeze)
  s.rubygems_version = "2.5.2".freeze
  s.summary = "TODO: one-line summary of your gem".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<semver>.freeze, ["~> 1"])
      s.add_runtime_dependency(%q<bunny>.freeze, ["~> 1"])
      s.add_runtime_dependency(%q<fxruby-enhancement>.freeze, ["~> 0"])
      s.add_runtime_dependency(%q<thor>.freeze, ["~> 0"])
      s.add_runtime_dependency(%q<awesome_print>.freeze, [">= 1"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3"])
      s.add_development_dependency(%q<yard>.freeze, ["~> 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry-byebug>.freeze, [">= 3"])
      s.add_development_dependency(%q<pry-doc>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry-remote>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry-rescue>.freeze, [">= 1"])
      s.add_development_dependency(%q<pry-stack_explorer>.freeze, [">= 0"])
    else
      s.add_dependency(%q<semver>.freeze, ["~> 1"])
      s.add_dependency(%q<bunny>.freeze, ["~> 1"])
      s.add_dependency(%q<fxruby-enhancement>.freeze, ["~> 0"])
      s.add_dependency(%q<thor>.freeze, ["~> 0"])
      s.add_dependency(%q<awesome_print>.freeze, [">= 1"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3"])
      s.add_dependency(%q<yard>.freeze, ["~> 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<pry-byebug>.freeze, [">= 3"])
      s.add_dependency(%q<pry-doc>.freeze, [">= 0"])
      s.add_dependency(%q<pry-remote>.freeze, [">= 0"])
      s.add_dependency(%q<pry-rescue>.freeze, [">= 1"])
      s.add_dependency(%q<pry-stack_explorer>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<semver>.freeze, ["~> 1"])
    s.add_dependency(%q<bunny>.freeze, ["~> 1"])
    s.add_dependency(%q<fxruby-enhancement>.freeze, ["~> 0"])
    s.add_dependency(%q<thor>.freeze, ["~> 0"])
    s.add_dependency(%q<awesome_print>.freeze, [">= 1"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3"])
    s.add_dependency(%q<yard>.freeze, ["~> 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<pry-byebug>.freeze, [">= 3"])
    s.add_dependency(%q<pry-doc>.freeze, [">= 0"])
    s.add_dependency(%q<pry-remote>.freeze, [">= 0"])
    s.add_dependency(%q<pry-rescue>.freeze, [">= 1"])
    s.add_dependency(%q<pry-stack_explorer>.freeze, [">= 0"])
  end
end

